
use strict;
use warnings;

use Module::Build 0.3601;

my %module_build_args = (
  'build_requires' => {
    'Module::Build' => '0.3601'
  },
  'configure_requires' => {
    'Module::Build' => '0.3601'
  },
  'dist_abstract' => 'Install modules currently used in all SHARYANTO\'s current applications',
  'dist_author' => [
    'Steven Haryanto <stevenharyanto@gmail.com>'
  ],
  'dist_name' => 'Task-BeLike-SHARYANTO-Apps',
  'dist_version' => '0.04',
  'license' => 'perl',
  'module_name' => 'Task::BeLike::SHARYANTO::Apps',
  'recommends' => {},
  'requires' => {
    'Algorithm::BinPack' => '0',
    'App::Options' => '0'
  },
  'script_files' => []
);


my $build = Module::Build->new(%module_build_args);

$build->create_build_script;
