---
abstract: "Install modules currently used in all SHARYANTO's current applications"
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 2.101040'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-SHARYANTO-Apps
recommends: {}
requires:
  Algorithm::BinPack: 0
  App::Options: 0
  Carp::Always: 0
  Crypt::PasswdMD5: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dump: 0
  Data::Schema: 0
  Date::Manip: 0
  Date::Parse: 0
  DateTime: 0
  DateTime::Format::DateManip: 0
  Digest::CRC: 0
  Email::Address: 0
  File::HomeDir: 0
  File::Slurp: 0
  File::Type: 0
  Finance::Bank::ID::BCA: 0
  Finance::Bank::ID::Mandiri: 0
  HTML::Parser: 0
  Image::Size: 0
  JSON: 0
  LWP: 0
  Lingua::Han::PinYin: 0
  List::MoreUtils: 0
  Log::Any::App: 0
  MIME::Parser: 0
  MP3::Tag: 0
  Mail::Internet: 0
  Mail::POP3Client: 0
  Mail::QmailQueue: 0
  Mail::Sender: 0
  Mail::Sendmail: 0
  Net::BitTorrent::File: 0
  Path::Class: 0
  Proc::PID::File: 0
  Proc::Reliable: 0
  Statistics::Descriptive: 0
  Term::ReadKey: 0
  Term::ReadLine: 0
  Text::Unaccent: 0
  Tie::Cache: 0
  URI: 0
  URI::Find: 0
  WWW::Google::Images: 0
  WWW::Mechanize: 0
  XML::RSSLite: 0
  YAML: 0
  YAML::Syck: 0
  YAML::Tiny: 0
  YAML::XS: 0
  autodie: 0
  iCal::Parser: 0
version: 0.01
